apiVersion: v1
kind: Secret
metadata:
  name: aiapp-minio-secret
  namespace: aiapp
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: aiapp
type: Opaque
stringData:
  MINIO_ROOT_USER: aiapp
  MINIO_ROOT_PASSWORD: CHANGE_ME_MINIO_PASSWORD
