apiVersion: v1
kind: Service
metadata:
  name: aiapp-identity-service
  namespace: aiapp
spec:
  selector:
    app: aiapp-identity-service
  ports:
    - name: http
      port: 80
      targetPort: http
